import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NODE_ENV: z.enum(["development", "test", "production"]),
    DATABASE_URL: z.string().min(1),
    AUTH_SECRET: z.string().min(1).default("dev-auth-secret-change-me"),
    AUTH_GOOGLE_ID: z.string().min(1).default("missing-google-client-id"),
    AUTH_GOOGLE_SECRET: z.string().min(1).default("missing-google-client-secret"),
    OPENAI_API_KEY: z.string().min(1).optional(),
    OPENAI_MODEL: z.string().min(1).default("gpt-4.1-mini"),
    PYTHON_BIN: z.string().min(1).default("../ML/venv/bin/python"),
    PYTHON_BRIDGE_PATH: z.string().min(1).default("../ML/integration_bridge.py"),
    PYTHON_BRIDGE_TIMEOUT_MS: z.coerce.number().int().min(30_000).max(3_600_000).default(480_000),
    STAGE1_MODEL_ARTIFACT: z.string().min(1).default("../ML/outputs/stage1_biomarker_simulation_full/stage1_biomarker_models.joblib"),
    STAGE1_METRICS_PATH: z.string().min(1).default("../ML/outputs/stage1_biomarker_simulation_full/stage1_validation_summary.csv"),
    STAGE2_MODEL_DIR: z.string().min(1).default("../ML/outputs/models"),
    UNCERTAINTY_A: z.coerce.number().default(0.45),
    UNCERTAINTY_B: z.coerce.number().default(0.35),
    UNCERTAINTY_C: z.coerce.number().default(0.2),
    UNCERTAINTY_LAMBDA: z.coerce.number().default(2),
    UNCERTAINTY_HORIZON: z.enum(["sqrt", "linear"]).default("sqrt"),
    UPLOAD_DIR: z.string().min(1).default("uploads"),
  },
  client: {
    NEXT_PUBLIC_APP_NAME: z.string().min(1).default("Medical Future Pipeline"),
  },
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    DATABASE_URL: process.env.DATABASE_URL,
    AUTH_SECRET: process.env.AUTH_SECRET,
    AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID,
    AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    OPENAI_MODEL: process.env.OPENAI_MODEL,
    PYTHON_BIN: process.env.PYTHON_BIN,
    PYTHON_BRIDGE_PATH: process.env.PYTHON_BRIDGE_PATH,
    PYTHON_BRIDGE_TIMEOUT_MS: process.env.PYTHON_BRIDGE_TIMEOUT_MS,
    STAGE1_MODEL_ARTIFACT: process.env.STAGE1_MODEL_ARTIFACT,
    STAGE1_METRICS_PATH: process.env.STAGE1_METRICS_PATH,
    STAGE2_MODEL_DIR: process.env.STAGE2_MODEL_DIR,
    UNCERTAINTY_A: process.env.UNCERTAINTY_A,
    UNCERTAINTY_B: process.env.UNCERTAINTY_B,
    UNCERTAINTY_C: process.env.UNCERTAINTY_C,
    UNCERTAINTY_LAMBDA: process.env.UNCERTAINTY_LAMBDA,
    UNCERTAINTY_HORIZON: process.env.UNCERTAINTY_HORIZON,
    UPLOAD_DIR: process.env.UPLOAD_DIR,
    NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
});
